# Generated by Django 3.2.8 on 2021-11-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
