# Generated by Django 3.2.8 on 2021-11-11 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('page_num', models.IntegerField(default=0)),
                ('book', models.ManyToManyField(to='first.Book')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
