# Generated by Django 3.2.8 on 2021-10-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
