# Generated by Django 3.2.8 on 2021-11-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_user_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_interaction',
            name='book',
        ),
        migrations.AddField(
            model_name='user_interaction',
            name='book',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='first.book'),
        ),
        migrations.RemoveField(
            model_name='user_interaction',
            name='user',
        ),
        migrations.AddField(
            model_name='user_interaction',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
