# Generated by Django 3.2.8 on 2021-10-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.TextField()),
                ('img_link', models.URLField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(unique=True)),
                ('rating', models.FloatField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('get', models.URLField(blank=True, null=True)),
                ('cloudflare', models.URLField(blank=True, null=True)),
                ('ipes', models.URLField(blank=True, null=True)),
                ('infura', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('intrest', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
