# Generated by Django 3.2.8 on 2021-10-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_book_user_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_features',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
